```{r}
# Load tidyverse and tidylog libraries
# Tidylog can be commented out if it isn't present, it just logs additional pertinent info on dplyr operations
library(tidyverse)
library(tidylog)

# Load the hashed merge library
source('hashed_merge.R')
```


```{r}
# Read in the two datasets
left_dataset <- NULL
right_dataset <- NULL
```


```{r}
# Define the hashed merge we want to use, using the HashedMerge and MergeField objects
# HashedMerge stores all of the logic about how to score variables, and is used to run individual rounds; we'll
# worry about defining the fields in a second. For now, we want to tell the MergeFields how to score the various types
# of fuzzy matches

# TODO: Explain that `merged` gets created by the program, don't need to manually add _left and _right suffixes

# First we'll define a standalone function to score matches on address; the correct form for these scoring functions is
# to take a single dataset (which I've called `merged` but you can call whatever) that has all of the PII for both
# sides of a candidate match which are indicated with the suffixes `_left` and `_right`; for example, `fn_left`,
# `fn_right`, `fn_sdx_left`, `fn_sdx_right`, `dob_y_left`, etc. This is created within the code; you do not need to
# create a dataframe like this, just write a function that accepts one. You will likely want to use a case_when for
# the bulk of the scoring function, and just assign scores based on various conditions, as we do now.

# `case_when` returns on the *first* true condition it encounters
# (in terms of the order in which you enter them), so you do not need to say that two fields are *not* equal
# for the sake of not overlapping with an earlier condition.
address_scoring_function <- function(merged){case_when(
  (merged['house_nb_left'] == merged['house_nb_right']) &
    (merged['predirection_cd_left'] == merged['predirection_cd_right']) &
    (merged['street_name_left'] == merged['street_name_right']) &
    (merged['street_suffix_left'] == merged['street_suffix_right']) &
    (merged['unit_type_left'] == merged['unit_type_right']) &
    (merged['unit_id_left'] == merged['unit_id_right']) &
    (merged['city_left'] == merged['city_right']) &
    (merged['zip_left'] == merged['zip_right']) &
    (merged['state_left'] == merged['state_right']) ~ 102,
  (merged['state_left'] == merged['state_right']) &
    (merged['zip_left'] == merged['zip_right']) &
    (merged['city_left'] == merged['city_right']) &
    (merged['street_name_left'] == merged['street_name_right']) &
    (merged['street_suffix_left'] == merged['street_suffix_right']) & (
      (merged['house_nb_left'] == merged['house_nb_right']) | (merged['unit_id_left'] == merged['unit_id_right']) 
    ) ~ 95,
  (merged['state_left'] == merged['state_right']) &
    (merged['zip_left'] == merged['zip_right']) &
    (merged['city_sdx_left'] == merged['city_sdx_right']) &
    (merged['city1l_left'] == merged['city1l_right']) &
    (merged['street_name_left'] == merged['street_name_right']) &
    (merged['street_suffix_left'] == merged['street_suffix_right']) & (
      (merged['house_nb_left'] == merged['house_nb_right']) | (merged['unit_id_left'] == merged['unit_id_right']) 
    ) ~ 85,
  (merged['state_left'] == merged['state_right']) &
    (merged['zip_left'] == merged['zip_right']) &
    (merged['city_left'] == merged['city_right']) &
    (merged['street_name_sdx_left'] == merged['street_name_sdx_right']) &
    (merged['street_name4l_left'] == merged['street_name4l_right']) &
    (merged['street_suffix_left'] == merged['street_suffix_right']) & (
      (merged['house_nb_left'] == merged['house_nb_right']) | (merged['unit_id_left'] == merged['unit_id_right']) 
    ) ~ 75,
  (merged['state_left'] == merged['state_right']) &
    (merged['zip_left'] == merged['zip_right']) &
    (merged['city_sdx_left'] == merged['city_sdx_right']) &
    (merged['street_name_sdx_left'] == merged['street_name_sdx_right']) &
    (merged['street_name4l_left'] == merged['street_name4l_right']) &
    (merged['street_suffix_left'] == merged['street_suffix_right']) & (
      (merged['house_nb_left'] == merged['house_nb_right']) | (merged['unit_id_left'] == merged['unit_id_right']) 
    ) ~ 65,
  (merged['state_left'] == merged['state_right']) &
    (merged['zip_left'] == merged['zip_right']) &
    (merged['city_sdx_left'] == merged['city_sdx_right']) &
    (merged['street_name_sdx_left'] == merged['street_name_sdx_right']) & (
      (merged['house_nb_left'] == merged['house_nb_right']) | (merged['unit_id_left'] == merged['unit_id_right']) 
    ) ~ 55,
  (merged['state_left'] == merged['state_right']) &
    (merged['city_left'] == merged['city_right']) &
    (merged['street_name_sdx_left'] == merged['street_name_sdx_right']) ~ 45,
  (merged['state_left'] == merged['state_right']) &
    (merged['city_sdx_left'] == merged['city_sdx_right']) &
    (merged['street_name_sdx_left'] == merged['street_name_sdx_right']) ~ 35,
  (merged['state_left'] == merged['state_right']) &
    (merged['street_name_sdx_left'] == merged['street_name_sdx_right']) ~ 25,
  (merged['street_name_sdx_left'] == merged['street_name_sdx_right']) &
    (merged['street_name4l_left'] == merged['street_name4l_right']) ~ 15,
  TRUE ~ 0
)}

# Create the HashedMerge object
hashed_merge <- HashedMerge(
  # Pass in the two datasets we're using
  # Because of quirks in R, you have to use named arguments (rather than positional) for all of the objects
  # we'll create, so just make sure to use left_df=, right_df=, etc
  left_df=left_dataset,
  right_df=right_dataset,
  # Define the list of merge fields - names, partial PII columns, scoring functions
  merge_fields=list(
    # For fn, ln, and dob we can just use the default MergeFields defined in hashed_merge.R - under the hood these are
    # just MergeField objects defined exactly like we will define the address field below. If you wanted to change
    # the scoring, or if you had more or fewer partial PII fields than the default for any of these fields, you would
    # just define a MergeField yourself rather than using the default.
    DEFAULT_FN_MERGE_FIELD,
    DEFAULT_LN_MERGE_FIELD,
    DEFAULT_DOB_MERGE_FIELD,
    # For address, we do not have a pre-defined default MergeField, so we create our own
    # (Again, you could just do this for all of the fields you're using to have finer control over the scoring; the
    # default fields are just for your convenience.)
    MergeField(
      # Name of the field is address
      name='address',
      # List all of the constituent partial fields for address
      partial_fields=list('house_nb', 'predirection_cd', 'street_name', 'street_suffix',
                       'unit_type', 'unit_id', 'city', 'zip', 'state'),
      # There is maybe a better term than "compound" but this flag indicates whether there is a column in the dataset
      # with the same name as the value you inputted for "name" in the arguments to this MergeField. For example,
      # `fn` is not a compound field, because there is a column called `fn` that indicates whether the candidate match
      # is a perfect match on that field. `dob` and `address` do not have single "dob" or "address" columns, and a
      # perfect match is defined as a match on all of the partial fields, and so we call them "compound" fields.
      is_compound=TRUE,
      # Pass the scoring function we defined above
      scoring_function=address_scoring_function
      )
  )
)
```


```{r}
# Now we define the rounds of matching we will use. Rounds are created using the `round` method of the HashedMerge
# object we defined above (which can be accessed with the `$` operator.) We define the rounds using two types of
# objects: Conditions and ConditionSets. Conditions are, for example perfect_match('fn'), or
# fuzzy_match('ln', min_score=20). A ConditionSet specifies the `and` or `or` logic across these conditions,
# for example that all_of_conditions or n_of_conditions must be true. Condition sets can be nested to allow for
# more complex logic.
# 
# This sounds more complicated than it is in practice! We'll now define the rounds.
# 
# You can store the results of the rounds however you want, like any other R object. The rounds return a dataframe
# containing a crosswalk from left_id to right_id. For simplicity, we'll just store them directly in a list
# (this is, ultimately, how they'll need to be stored if you want to use the postprocessing functions to generate
# a single crosswalk and stats on the matching.)

rounds <- list(
  `0`=hashed_merge$round(
    # First define the join keys - literally the fields that will be used to initially join the two datasets.
    # Any field that must always be exactly equal can be included here. You probably want to include as many fields as
    # possible here; the overall process is that the two datasets are joined by the join keys, and then the
    # other_conditions are evaluated on the joined dataframe, so including as many join keys as possible will cut down
    # on the amount of computation that needs to be done in the other_conditions (and the overall time) dramatically.
    # A nice feature of the MergeFields is that, since they know what partial fields go into a field, you do not need
    # to write out every partial field of address to use it as a join key; you can just say 'address' and the
    # logic in HashedMerge will take care of converting that to all of the partial fields (same for DOB).
    join_keys=c('fn', 'ln', 'dob', 'address')
    # Since this round is only all perfect matches, we don't actually need to pass anything for other_conditions;
    # this round is done.
  ),
  `1`=hashed_merge$round(
    # This round is perfect match on fn, ln, address, and fuzzy match on DOB, so use the first three as join keys
    join_keys=c('fn', 'ln', 'address'),
    # We'll wrap the lone fuzzy_match condition in an all_of, since `round` expects a ConditionSet (all_of_conditions or
    # n_of_conditions) rather than a Condition (perfect_match or fuzzy_match).
    # We can define a min_score that constitutes a successful fuzzy match; we'll set it to 1, which means any
    # two components of DOB match. You'll need to reference the scoring function for a field to set this value
    # in a way that corresponds to your desired level of match.
    other_conditions=all_of_conditions(fuzzy_match('dob', min_score=1))
  ),
  `2`=hashed_merge$round(
    # This round is perfect match on DOB, perfect match on two of FN/LN/address, and fuzzy match on whichever
    # doesn't perfect match. Since DOB is the only field that must unconditionally match perfectly, it's our only join
    # key for this round.
    join_keys=c('dob'),
    # Now we have to figure out how to represent the rest of the logic - since a perfect match is also a successful
    # fuzzy match at any score threshold, we can represent "perfect match on 2/3 of these fields and fuzzy match on the
    # other" as "perfect match on 2/3 of these fields and fuzzy match on all of them".
    other_conditions=all_of_conditions(
      # We'll use the nested condition sets mentioned earlier here - (perfect match on 2/3) and (fuzzy match on all 3)
      # are essentially two different sets of conditions, and we need them both to be true, hence wrapping them in an
      # all_of_conditions above
      # First represent the perfect match on 2/3 using n_of_conditions
      n_of_conditions(
        perfect_match('fn'),
        perfect_match('ln'),
        perfect_match('address'),
        n=2
      ),
      # Now add the fuzzy match on all 3 condition set
      all_of_conditions(
        # For fn/ln, assume we want any fuzzy match so set min_score to 1
        fuzzy_match('fn', min_score=1),
        fuzzy_match('ln', min_score=1),
        # For address we want at least a match on state/city/street; this condition isn't explicitly given a score
        # in the address scoring function, so we'll use 35 (state, city, street soundex) for now
        fuzzy_match('address', min_score=35)
      )
    )
  ),
  `3`=hashed_merge$round(
    # Round 3 is perfect match on DOB and 2/3 of (fn, ln address), which is easy to represent with a join key of
    # DOB and n_of_conditions for the other part of the condition set
    join_keys=c('dob'),
    other_conditions=n_of_conditions(
      perfect_match('fn'),
      perfect_match('ln'),
      perfect_match('address'),
      n=2
    )
  ),
  `4`=hashed_merge$round(
    # Round 4 is perfect match on address, perfect match on two of (fn, ln, dob), and fuzzy match on whichever
    # didn't perfect match; we do this the same way we did round 2
    join_keys=c('address'),
    other_condtions=all_of_conditions(
      n_of_conditions(
        perfect_match('fn'),
        perfect_match('ln'),
        perfect_match('dob'),
        n=2
      ),
      all_of_conditions(
        fuzzy_match('fn', min_score=1),
        fuzzy_match('ln', min_score=1),
        fuzzy_match('dob', min_score=35)
      )
    )
  ),
  `5`=hashed_merge$round(
    # Round 5 is perfect match on address, and perfect match on 2/3 of (fn, ln, dob)
    join_keys=c('address'),
    other_conditions=n_of_conditions(
      perfect_match('fn'),
      perfect_match('ln'),
      perfect_match('dob')
    )
  ),
  `6`=hashed_merge$round(
    # Perfect match on DOB, perfect match on 1 of fn/ln/address, fuzzy match on the others
    join_keys=c('dob'),
    other_conditions=all_of_conditions(
      n_of_conditions(
        perfect_match('fn'),
        perfect_match('ln'),
        perfect_match('address'),
        n=1
      ),
      all_of_conditions(
        fuzzy_match('fn', min_score=1),
        fuzzy_match('ln', min_score=1),
        fuzzy_match('address', min_score=35)
      )
    )
  ),
  `7`=hashed_merge$round(
    # Perfect match on address, perfect match on 1 of fn/ln/dob, fuzzy match on the others
    join_keys=c('address'),
    other_conditions=all_of_conditions(
      n_of_conditions(
        perfect_match('fn'),
        perfect_match('ln'),
        perfect_match('dob'),
        n=1
      ),
      all_of_conditions(
        fuzzy_match('fn', min_score=1),
        fuzzy_match('ln', min_score=1),
        fuzzy_match('dob', min_score=1)
      )
    )
  ),
  `8`=hashed_merge$round(
    # Perfect match on DOB, fuzzy match on fn/ln/address
    join_keys=c('dob'),
    other_conditions=all_of(
      fuzzy_match('fn', min_score=1),
      fuzzy_match('ln', min_score=1),
      fuzzy_match('address', min_score=1))
  ),
  `9`=hashed_merge$round(
    # Perfect match on fn/ln, fuzzy match on address
    join_keys=c('fn', 'ln'),
    other_conditions=all_of(fuzzy_match('address', min_score=35))
  )
)
```


```{r}
# Now pass the results to the postprocessing function, which outputs the final crosswalk and some diagnostics
generate_match_outputs(rounds, left_name='left dataset name', right_name='right dataset name', write_crosswalk=TRUE,
                       dir='your output directory here', prefix='you can add a filename prefix here', suffix='')
```

